name: Transport Cables
run-name: Transport Cables
on: [push]
jobs:
  Transport-Cables:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate sprites
        run: python generate_sprites.py

      - name: Archive generated sprites
        uses: actions/upload-artifact@v3
        with:
          name: sprites
          path: sprites

      - name: Extract mod version from info.json
        # if: github.ref_type == 'tag'
        id: get_mod_version
        run: |
          MOD_VERSION=$(grep -i '\"version\":' info.json | grep -o '[0-9].[0-9].[0-9]')
          echo "MOD_VERSION = ${MOD_VERSION}"
          echo "mod_version=${MOD_VERSION}" >> $GITHUB_OUTPUT

      - name: Create release
        if: github.ref_type == 'tag'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          release_name: transport-cables-${{ github.ref }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md

      - name: Create mod .zip folder
        if: github.ref_type == 'tag'
        run: |
          mkdir ./transport-cables_${{ steps.get_mod_version.outputs.mod_version }}
          cp -r {locale/,prototypes/,sprites/,*.lua,info.json} ./transport-cables_${{ steps.get_mod_version.outputs.mod_version }}/
          zip -r ./transport-cables_${{ steps.get_mod_version.outputs.mod_version }}.zip ./transport-cables_${{ steps.get_mod_version.outputs.mod_version }}/
          ls .

      - name: Add mod .zip folder to release
        if: github.ref_type == 'tag'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./transport-cables_${{ steps.get_mod_version.outputs.mod_version }}.zip
          asset_name: transport-cables_${{ steps.get_mod_version.outputs.mod_version }}.zip
          asset_content_type: application/gzip
