name: Transport Cables
run-name: Transport Cables
on: [push]
jobs:
  Transport-Cables:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate sprites
        run: python generate_sprites.py

      - name: Archive generated sprites
        uses: actions/upload-artifact@v3
        with:
          name: sprites
          path: sprites

      - name: Extract mod version from info.json
        if: github.ref_type == 'tag'
        id: get_mod_version
        run: |
          MOD_VERSION=$(grep -i '\"version\":' info.json | grep -o '[0-9].[0-9].[0-9]')
          echo "MOD_VERSION = ${MOD_VERSION}"
          echo "mod_version=${MOD_VERSION}" >> $GITHUB_OUTPUT

      - name: Create mod .zip
        run: zip -r ${MOD_VERSION}.zip locale/ prototypes/ sprites/ *.lua info.json
